<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            [
                'name' => 'Colombia',
                'iso2' => 'CO',
                'iso3' => 'COL',
                'phone_code' => '+57',
                'capital' => 'Bogotá',
                'currency' => 'Peso colombiano',
                'currency_code' => 'COP',
                'currency_symbol' => '$',
                'region' => 'América',
                'subregion' => 'América del Sur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Estados Unidos',
                'iso2' => 'US',
                'iso3' => 'USA',
                'phone_code' => '+1',
                'capital' => 'Washington D.C.',
                'currency' => 'Dólar estadounidense',
                'currency_code' => 'USD',
                'currency_symbol' => '$',
                'region' => 'América',
                'subregion' => 'América del Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'México',
                'iso2' => 'MX',
                'iso3' => 'MEX',
                'phone_code' => '+52',
                'capital' => 'Ciudad de México',
                'currency' => 'Peso mexicano',
                'currency_code' => 'MXN',
                'currency_symbol' => '$',
                'region' => 'América',
                'subregion' => 'América del Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'España',
                'iso2' => 'ES',
                'iso3' => 'ESP',
                'phone_code' => '+34',
                'capital' => 'Madrid',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'region' => 'Europa',
                'subregion' => 'Europa del Sur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Argentina',
                'iso2' => 'AR',
                'iso3' => 'ARG',
                'phone_code' => '+54',
                'capital' => 'Buenos Aires',
                'currency' => 'Peso argentino',
                'currency_code' => 'ARS',
                'currency_symbol' => '$',
                'region' => 'América',
                'subregion' => 'América del Sur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Brasil',
                'iso2' => 'BR',
                'iso3' => 'BRA',
                'phone_code' => '+55',
                'capital' => 'Brasilia',
                'currency' => 'Real brasileño',
                'currency_code' => 'BRL',
                'currency_symbol' => 'R$',
                'region' => 'América',
                'subregion' => 'América del Sur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chile',
                'iso2' => 'CL',
                'iso3' => 'CHL',
                'phone_code' => '+56',
                'capital' => 'Santiago',
                'currency' => 'Peso chileno',
                'currency_code' => 'CLP',
                'currency_symbol' => '$',
                'region' => 'América',
                'subregion' => 'América del Sur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Perú',
                'iso2' => 'PE',
                'iso3' => 'PER',
                'phone_code' => '+51',
                'capital' => 'Lima',
                'currency' => 'Sol peruano',
                'currency_code' => 'PEN',
                'currency_symbol' => 'S/',
                'region' => 'América',
                'subregion' => 'América del Sur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Venezuela',
                'iso2' => 'VE',
                'iso3' => 'VEN',
                'phone_code' => '+58',
                'capital' => 'Caracas',
                'currency' => 'Bolívar soberano',
                'currency_code' => 'VES',
                'currency_symbol' => 'Bs.',
                'region' => 'América',
                'subregion' => 'América del Sur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ecuador',
                'iso2' => 'EC',
                'iso3' => 'ECU',
                'phone_code' => '+593',
                'capital' => 'Quito',
                'currency' => 'Dólar estadounidense',
                'currency_code' => 'USD',
                'currency_symbol' => '$',
                'region' => 'América',
                'subregion' => 'América del Sur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('countries')->insert($countries);
    }
}
